"""
LSTM forecaster training loop.

Supports both clean (baseline) and GAN-augmented (robust) training.
"""

from __future__ import annotations

import logging
import os

import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import DataLoader
from tqdm import tqdm

from robustlmp_gan.models import Generator, LSTMForecaster

logger = logging.getLogger(__name__)


def train_forecaster(
    train_loader: DataLoader,
    val_loader: DataLoader,
    n_features: int,
    G: Generator | None = None,
    noise_dim: int = 32,
    lstm_hidden: int = 64,
    lstm_layers: int = 2,
    dropout: float = 0.2,
    lr: float = 1e-3,
    epochs: int = 25,
    augment: bool = False,
    aug_eps_range: list[float] | None = None,
    aug_fraction: float = 0.3,
    grad_clip: float = 1.0,
    scheduler_patience: int = 3,
    scheduler_factor: float = 0.5,
    output_dir: str = "robustlmp_outputs",
    tag: str = "baseline",
) -> tuple[LSTMForecaster, list[float], list[float]]:
    """Train an LSTMForecaster with optional GAN-based data augmentation.

    When ``augment=True``, a fraction of each batch is replaced with
    adversarially perturbed versions generated by ``G``. The epsilon
    value is sampled uniformly from ``aug_eps_range`` each batch,
    ensuring the model sees a broad distribution of perturbation magnitudes.

    Args:
        train_loader: Training DataLoader.
        val_loader: Validation DataLoader.
        n_features: Number of input features.
        G: Pre-trained Generator. Required when ``augment=True``.
        noise_dim: Noise vector dimension for the Generator.
        lstm_hidden: LSTM hidden size.
        lstm_layers: Number of LSTM layers.
        dropout: LSTM dropout rate.
        lr: Learning rate.
        epochs: Training epochs.
        augment: If True, apply GAN augmentation.
        aug_eps_range: List of epsilon values to sample from when
            augmenting. Required when ``augment=True``.
        aug_fraction: Fraction of each batch to augment.
        grad_clip: Gradient clipping norm.
        scheduler_patience: Epochs before LR reduction.
        scheduler_factor: LR reduction factor.
        output_dir: Directory for saving model weights.
        tag: Short label used in filenames and logging (e.g. ``"baseline"``
            or ``"robust"``).

    Returns:
        Tuple of ``(best_model, train_loss_history, val_loss_history)``.

    Raises:
        ValueError: If ``augment=True`` but ``G`` or ``aug_eps_range``
            is not provided.
    """
    if augment and G is None:
        raise ValueError("Generator G must be provided when augment=True")
    if augment and not aug_eps_range:
        raise ValueError("aug_eps_range must be provided when augment=True")

    os.makedirs(output_dir, exist_ok=True)
    best_path = os.path.join(output_dir, f"lstm_{tag}_best.pt")

    model = LSTMForecaster(n_features, lstm_hidden, lstm_layers, dropout)
    opt = torch.optim.Adam(model.parameters(), lr=lr)
    sched = torch.optim.lr_scheduler.ReduceLROnPlateau(
        opt, patience=scheduler_patience, factor=scheduler_factor
    )
    loss_fn = nn.HuberLoss()

    best_val = float("inf")
    train_hist: list[float] = []
    val_hist: list[float] = []

    logger.info(
        "Training LSTM [%s] | augment=%s | epochs=%d", tag, augment, epochs
    )

    for epoch in range(epochs):
        # ── Train ─────────────────────────────────────────────────────
        model.train()
        train_losses: list[float] = []

        for x_seq, y_rt, y_da in tqdm(
            train_loader,
            desc=f"  Epoch {epoch + 1:2d}/{epochs} [{tag}]",
            leave=False,
        ):
            if augment and G is not None and aug_eps_range:
                n_aug = int(x_seq.size(0) * aug_fraction)
                if n_aug > 0:
                    eps = float(np.random.choice(aug_eps_range))
                    z = torch.randn(n_aug, noise_dim)
                    with torch.no_grad():
                        delta = G(z)
                    x_aug = (x_seq[:n_aug] + delta * eps).clamp(0, 1)
                    x_seq = torch.cat([x_seq, x_aug], dim=0)
                    y_rt = torch.cat([y_rt, y_rt[:n_aug]], dim=0)
                    y_da = torch.cat([y_da, y_da[:n_aug]], dim=0)

            opt.zero_grad()
            pred_rt, pred_da = model(x_seq)
            loss = loss_fn(pred_rt, y_rt) + loss_fn(pred_da, y_da)
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), grad_clip)
            opt.step()
            train_losses.append(loss.item())

        # ── Validate ──────────────────────────────────────────────────
        model.eval()
        val_losses: list[float] = []
        with torch.no_grad():
            for x_seq, y_rt, y_da in val_loader:
                pred_rt, pred_da = model(x_seq)
                loss = loss_fn(pred_rt, y_rt) + loss_fn(pred_da, y_da)
                val_losses.append(loss.item())

        t_loss = float(np.mean(train_losses))
        v_loss = float(np.mean(val_losses))
        train_hist.append(t_loss)
        val_hist.append(v_loss)
        sched.step(v_loss)

        if v_loss < best_val:
            best_val = v_loss
            torch.save(model.state_dict(), best_path)

        if (epoch + 1) % 5 == 0:
            logger.info(
                "  Epoch [%d/%d] Train=%.4f Val=%.4f Best=%.4f",
                epoch + 1,
                epochs,
                t_loss,
                v_loss,
                best_val,
            )

    # Restore best weights
    model.load_state_dict(torch.load(best_path))
    logger.info("Training complete [%s] — best val=%.4f", tag, best_val)
    return model, train_hist, val_hist
